### ISSUE TITLE
Installation failed before installing numpy

### ISSUE THREAD

**Issue by the0demiurge** [luispedro/imread#26]
```Collecting imread (from -r requirements.txt (line 9))
Downloading imread-0.6.tar.gz (116kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-z49ubwd6/imread/setup.py", line 19, in <module>
import numpy as np
ImportError: No module named 'numpy'

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z49ubwd6/imread
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error: build error: non-zero (13) exit code from registry.access.redhat.com/rhscl/python-35-rhel7@sha256:ba3115fddc7aece697d11dabfa6463c337725e00e088fe9cc4f51f8f2a1f801b
```

**Comment by the0demiurge** [comment]
The repo is already fixed but pypi doesn't update
